version: "3.3"
services:
  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./src:/src

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "php"

  nginx:
    container_name: nginx
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./src:/src/
      - ./hosts/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/logs/nginx
    depends_on:
      - "php"
      - "adminer"

  # if u need postgres...

  # postgres:
  #   container_name: postgres
  #   image: postgres:9.5
  #   restart: always
  #  volumes:
  #    - ./db:/docker-entrypoint-initdb.d
  #   ports:
  #     - 5432:5432   
  #   environment:
  #     POSTGRES_DB: base
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306   
    environment:
      MYSQL_DATABASE: base
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - "php"