version: "3.7"
services:

  # apache:
  #   container_name: apache
  #   image: httpd:latest
  #   ports:
  #     - "732:80"
  #   volumes:
  #     - ../../www/bitrix:/usr/local/apache2/htdocs
  #     # - ./hosts/apache2:/usr/local/apache2/conf
  #     - ./logs/apache2:/usr/local/apache2/logs
  #   depends_on:
  #     - php

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "740:740"
      - "741:741"
      - "742:742"
    volumes:
      - ../../www:/var/www
      - ./hosts/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - internal

  php:
    container_name: php
    build: ./images/php
    volumes:
      - ../../www:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
      
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
    # links:
    #    - mysql:db

  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   ports: 
  #     - "3306:3306"
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - mysql:db