version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.17
    ports:
      - 789:80
    volumes:
      - ./src:/src/
      - ./hosts/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/logs/nginx

  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./src:/src

  postgres:
    container_name: postgres
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 987:8080