version: "3.3"
services:
  php:
    container_name: php
    build: ./services/php
    env_file:
      - ./services/php/php.ini.env
    volumes:
      - ./services/php/log:/var/log/php
      - ./src:/var/www
    networks:
      - internal

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - php
    networks:
      - internal

  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - 81:81
    volumes:
      - ./services/nginx/log:/var/log/nginx
      - ./src:/var/www
    networks:
      - internal

  mysql:
    container_name: mysql
    build: ./services/mysql
    restart: always
    volumes:
      - ./services/mysql/log:/var/log/mysql
      - ./services/mysql/data:/var/backups/mysql
    ports:
      - 3306:3306
    env_file:
      - ./services/mysql/mysql.env
    networks:
      - internal


#    postgres:
#      container_name: postgres
#      image: postgres:9.5
#      restart: always
#      volumes:
#        - ./db:/docker-entrypoint-initdb.d
#      ports:
#        - 5432:5432
#      environment:
#        POSTGRES_DB: base
#        POSTGRES_USER: admin
#        POSTGRES_PASSWORD: admin
#      networks:
#        - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28